import type { Metadata } from 'next'
import {
  ColorSchemeScript,
  MantineProvider,
  DEFAULT_THEME,
  createTheme,
} from '@mantine/core';
import { Inter, JetBrains_Mono } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl'
import { unstable_setRequestLocale, getMessages } from 'next-intl/server'
import React, { ReactNode } from 'react';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const jetbrains_mono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains-mono',
  display: 'swap',
})

interface Props {
  children: ReactNode
  params: { locale: string }
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const theme = createTheme({
  fontFamily: `${inter.variable}, ${DEFAULT_THEME.fontFamily}`,
  fontFamilyMonospace: `${jetbrains_mono.variable}, ${DEFAULT_THEME.fontFamilyMonospace}`,
  headings: {
    fontFamily: `${inter.variable}, ${DEFAULT_THEME.fontFamily}`,
  },
  primaryColor: 'cyan',
  primaryShade: { light: 7, dark: 3 },

})

export default async function LocaleRootLayout({
  children,
  params: { locale },
}: Props) {
  unstable_setRequestLocale(locale)

  const messages = await getMessages()

  return (
    <html suppressHydrationWarning lang={locale}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <NextIntlClientProvider messages={messages}>
        <body>
          <MantineProvider defaultColorScheme="auto" theme={theme}>
            {children}
          </MantineProvider>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
